### ISSUE TITLE
[PULL] xfail/xpass/skip

### ISSUE THREAD

**Issue by navytux** [apenwarr/wvtest#2]
[ Duplicating here, since mailing patches via email got silence... ]

Hello Avery,

If it still makes sense, I'm finally here with updated xfail/xpass/skip
patches. Changes since last posting in 2010 are as follows:

```
1) don't touch colors in mstime (if I recall correctly, it was only my
   preference);

2) colorize_as() is used for emitting all results, and policy what goes in
   color and what not is localized to that function;

3) changed final printout to emit new info on separate line, e.g.

    WvTest: <n> tests skipped, <n> known breakages, <n> fixed breakages.

4) documented xfail/xpass/skip in README;

5) added xfail/xpass/skip to samples;

6) added XFAIL/SKIP to all drivers;

7) cosmetics.
```

That was it - I took your comments and adjusted changes and implemented
xfail/xpass support in drivers so that the feature could be easily used,
updated README.

Sorry for so long delay with replying. Hope it is still could be useful.
Please apply via:

```
git pull  git://repo.or.cz/wvtest/kirr.git  y2/xfail
```

Thanks,
Kirill

**Comment by apenwarr** [comment]
Merged.  Sorry for the extremely long delay :)

**Comment by navytux** [comment]
Wow, at last! Thanks for feedback.
